steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/concrete-wow:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/concrete-wow:$SHORT_SHA', 'gcr.io/$PROJECT_ID/concrete-wow:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/concrete-wow:$SHORT_SHA', 'gcr.io/$PROJECT_ID/concrete-wow:$BRANCH_NAME']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/concrete-wow:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/concrete-wow:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/concrete-wow:$BRANCH_NAME']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'beta', 'run', 'deploy', '--region', 'europe-west1', '--image', 'gcr.io/$PROJECT_ID/concrete-wow', '--platform', 'managed', 'concrete-wow' ]
images:
- 'gcr.io/$PROJECT_ID/concrete-wow'
